spring.application.name=java-api-with-otlp-sdk
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.tracing.transport=http
management.otlp.metrics.export.url=${OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
management.otlp.metrics.export.enabled=true
management.otlp.logging.endpoint=${OTLP_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
management.otlp.logging.transport=http
management.otlp.logging.export.enabled=true
management.opentelemetry.resource-attributes.service.name=${spring.application.name}
management.opentelemetry.resource-attributes.deployment.environment=${APP_ENV:local}
management.opentelemetry.resource-attributes.service.version=${APP_VERSION:0.0.1-SNAPSHOT}

springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.path=/api/v1/swagger-ui
springdoc.swagger-ui.url=/api/v1/api-docs
